name: resotone_web
description: Flutter Web platform implementation of Resonance + Omnitone
homepage: https://github.com/MichealReed/resotone
version: 0.0.1

dev_dependencies:
  benchmark_harness: '>=1.0.0 <1.1.0'
  test: '>=1.2.0 <2.0.0'
environment:
  sdk: '>=2.0.0 <3.0.0'